name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          # Removed npm cache as there's no package.json
      
      - name: Verify Files
        run: |
          echo "Verifying critical files for deployment..."
          if [ -f "index.html" ] && [ -f "404.html" ]; then 
            echo "✅ HTML files verified."
          else 
            echo "❌ Critical HTML files missing!" && exit 1
          fi
          
      - name: Configure Git
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: .
          branch: gh-pages
          clean: true
